Controllers/BookingController.cs
using CodeFirstVenueBooking.Models;
using CodeFirstVenueBooking.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace CodeFirstVenueBooking.Controllers
{
    public class BookingController : Controller
    {


        IBookingRepo repository;
        public BookingController(IBookingRepo repo)
        {
            this.repository = repo;
        }
        public IActionResult Index()
        {
            return View(repository.GetAllBookings());
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Booking booking)
        {
            repository.UpdateBooking(booking);
            return RedirectToAction("Index");
        }
        public IActionResult Edit(int id)
        {
            Booking booking = repository.GetBookingById(id);
            if (booking != null)
                return View(booking);
            else

                return NotFound();
        }
        [HttpPost]
        public IActionResult Edit(Booking booking)
        {
            repository.UpdateBooking(booking);
            return RedirectToAction("Index");

        }
        public IActionResult Delete(int id)
        {
            Booking booking = repository.GetBookingById(id);
            if (booking != null)
                return View(booking);
            else

                return NotFound();
        }
        [HttpPost]
        public IActionResult Delete(Booking booking)
        {
            repository.DeleteBooking(booking.Bno);
            return RedirectToAction("Index");

        }

    }
}

Controllers/CustomerEventDetailsController.cs
using CodeFirstVenueBooking.Models;
using CodeFirstVenueBooking.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace CodeFirstVenueBooking.Controllers
{
    public class CustomerEventDetailsController : Controller
    {
        ICustomerEDRepo repository;
        public CustomerEventDetailsController(ICustomerEDRepo repo)
        {
            this.repository = repo;
        }
        public IActionResult Index()
        {
            return View(repository.GetAllCustomerEventDetails());
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(CustomerEventDetails customerEventDetails)
        {
            repository.AddNewCustomerEventDetails(customerEventDetails);
            return RedirectToAction("Index");
        }
        public IActionResult Edit(string name)
        {
            CustomerEventDetails customerEventDetails = repository.GetCustomerEventDetailsById(name);
            if (customerEventDetails != null)
                return View(customerEventDetails);
            else

                return NotFound();
        }
        [HttpPost]
        public IActionResult Edit(CustomerEventDetails customerEventDetails)
        {
            repository.UpdateCustomerEventDetails(customerEventDetails);
            return RedirectToAction("Index");

        }
        public IActionResult Delete(string name)
        {
            CustomerEventDetails customerEventDetails = repository.GetCustomerEventDetailsById(name);
            if (customerEventDetails != null)
                return View(customerEventDetails);
            else

                return NotFound();
        }
        [HttpPost]
        public IActionResult Delete(CustomerEventDetails customerEventDetails)
        {
            repository.DeleteCustomerEventDetails(customerEventDetails.EventName);
            return RedirectToAction("Index");

        }
    }
}

Controllers/DecorationController.cs
using CodeFirstVenueBooking.Models;
using CodeFirstVenueBooking.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace CodeFirstVenueBooking.Controllers
{
    public class DecorationController : Controller
    {
        IDecorationRepo repository;
        public DecorationController(IDecorationRepo repo)
        {
            this.repository = repo;
        }

        public IActionResult Index()
        {
            return View(repository.GetAllDecorations());
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Decoration decoration)
        {
            repository.AddNewDecoration(decoration);
            return RedirectToAction("Index");

        }
        public IActionResult Edit(int id)
        {
            Decoration decoration = repository.GetDecorationById(id);
            if(decoration!=null)
                return View(decoration);
            else

                return NotFound();
        }
        [HttpPost]
        public IActionResult Edit(Decoration decoration)
        {
            repository.UpdateDecoration(decoration);
            return RedirectToAction("Index");

        }

        

        public IActionResult Delete(int id)
        {
            Decoration decoration = repository.GetDecorationById(id);
            if (decoration != null)
                return View(decoration);
            else

                return NotFound();
        }
        [HttpPost]
        public IActionResult Delete(Decoration decoration)
        {
            repository.DeleteDecoration(decoration.Id);
            return RedirectToAction("Index");

        }
    }
}

Controllers/PaymentController.cs
using CodeFirstVenueBooking.Models;
using Microsoft.AspNetCore.Mvc;
using CodeFirstVenueBooking.Repositories;

namespace CodeFirstVenueBooking.Controllers
{
    public class PaymentController : Controller
    {
        IPaymentRepo repository;
        public PaymentController(IPaymentRepo repo)
        {
            this.repository = repo;
        }

        public IActionResult Index()
        {
            return View(repository.GetAllPayments());
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Payment payment)
        {
            repository.AddNewPayment(payment);
            return RedirectToAction("Index");
        }
        public IActionResult Edit(int id)
        {
            Payment payment = repository.GetPaymentById(id);
            if (payment != null)
                return View(payment);
            else

                return NotFound();
        }
        [HttpPost]
        public IActionResult Edit(Payment payment)
        {
            repository.UpdatePayment(payment);
            return RedirectToAction("Index");

        }
        public IActionResult Delete(int id)
        {
            Payment payment = repository.GetPaymentById(id);
            if (payment != null)
                return View(payment);
            else

                return NotFound();
        }
        [HttpPost]
        public IActionResult Delete(Payment payment)
        {
            repository.DeletePayment(payment.Bno);
            return RedirectToAction("Index");

        }
    }   
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CodeFirstVenueBooking</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CodeFirstVenueBooking</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Booking" asp-action="Index">Booking</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Decoration" asp-action="Index">Decoration</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CustomerEventDetails" asp-action="Index">CustomerEventDetails</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Payment" asp-action="Index">Payment</a>
                        </li>
                    </ul>
                    
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CodeFirstVenueBooking - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>